#ifndef LLP_LAB1_CONFIG_H
#define LLP_LAB1_CONFIG_H



#define INITIAL_FILE_SIZE 16384
#define BLOCK_MIN_CAPACITY 64
#define GRAPH_NODES_PER_BLOCK 1000
#define GRAPH_LINKS_PER_BLOCK 1000

#endif //LLP_LAB1_CONFIG_H
